version: '3.8'

services:
  hadoop-master:
    image: liliasfaxi/hadoop-cluster:latest
    container_name: hadoop-master
    hostname: hadoop-master
    ports:
      - "9870:9870"
      - "8088:8088"
      - "7077:7077"
      - "16010:16010"
    networks:
      - hadoop
    command: bash -c "service ssh start && tail -f /dev/null"

  hadoop-worker1:
    image: liliasfaxi/hadoop-cluster:latest
    container_name: hadoop-worker1
    hostname: hadoop-worker1
    ports:
      - "8040:8042"
    networks:
      - hadoop
    command: bash -c "service ssh start && tail -f /dev/null"

  hadoop-worker2:
    image: liliasfaxi/hadoop-cluster:latest
    container_name: hadoop-worker2
    hostname: hadoop-worker2
    ports:
      - "8041:8042"
    networks:
      - hadoop
    command: bash -c "service ssh start && tail -f /dev/null"

networks:
  hadoop:
    driver: bridge
